### PR TITLE
Parallelize log collection

### PR DESCRIPTION
**Pull request by jibi**
Use a pool of threads (with a size equal to the number of CPUs + 4) to
run in parallel the different log collection actions.

This should improve the execution speed.

Signed-off-by: Gilberto Bertin <gilberto@isovalent.com>

### CODE REVIEW

**Review by christarazi — COMMENTED** [review]
The changes look good to me. I tried it out on an EKS cluster with 2 nodes, all default settings, and I got 42s with this PR vs 24s on `master` :thinking:.

I wonder why that is...~~maybe we need to use multiprocessing instead of threading because each "task" is executing a separate `kubectl` process and that makes it more CPU-bound?~~ (I see we are already using `multiprocessing`)

**Comment by jibi** [comment]
I also redid the test on an freshly spanwed EKS cluster but wasn't able to reproduce your numbers :thinking: 

```sh
➜  cilium-sysdump git:(pr/jibi/parallel-logs-collection) time python cilium-sysdump.zip > /dev/null
python cilium-sysdump.zip > /dev/null  77,55s user 8,48s system 140% cpu 1:01,36 total

➜  cilium-sysdump git:(master) time python cilium-sysdump.zip > /dev/null
python cilium-sysdump.zip > /dev/null  76,39s user 8,23s system 152% cpu 55,534 total
```

I still don't see any performance gain, but I guess there's little margin for improvements to show up in a small (and unused) cluster

**Comment by jibi** [comment]
I tested again this branch on a freshly spawned EKS cluster and I can see indeed that it's taking a bit longer to collect all the logs (not almost 50% as in your case though):

```sh
➜  cilium-sysdump git:(master) time python cilium-sysdump.zip > /dev/null
python cilium-sysdump.zip > /dev/null  67,84s user 7,98s system 58% cpu 2:10,26 total

➜  cilium-sysdump git:(pr/jibi/parallel-logs-collection) time python cilium-sysdump.zip > /dev/null
python cilium-sysdump.zip > /dev/null  76,02s user 8,27s system 136% cpu 1:01,88 total
```

I guess we should test these changes on a real cluster with a reasonable size as maybe a 2 nodes cluster which is mostly unused does not have much room for performance improvements?

**Review by Rolinh — APPROVED** [review]
:100: 

On a 4 nodes kind cluster, before the PR:
```
python cilium-sysdump.zip  14.77s user 4.22s system 158% cpu 11.974 total
```

With the changes in this PR:
```
python cilium-sysdump.zip  11.63s user 3.15s system 214% cpu 6.896 total
```

**Review by christarazi — APPROVED** [review]

**Pull request merged**
