### PR TITLE
add support for multiple containers per pods

### PR DESCRIPTION
**Pull request by Rolinh**
If a pod contains multiple containers, cilium-sysdumps now gather logs and gops data for each individual container.

### CODE REVIEW

**Comment by genbit** [comment]
@Rolinh tested, works for me.

**Comment by tgraf** [comment]
Rebased to resolve conflict

**Comment by tgraf** [comment]
@genbit Would be great if you can give this another spin as you seem to run the setup which requires this

**Comment by genbit** [comment]
@tgraf tested, it works

**Pull request merged**
